# Generated by Django 5.2.7 on 2026-01-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tableau_de_bord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendementParZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('culture', models.CharField(max_length=50)),
                ('rendement_total', models.FloatField(help_text='Rendement total en tonnes')),
            ],
        ),
    ]
