# Generated by Django 5.2.7 on 2026-01-21 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recolte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_culture', models.CharField(choices=[('MAIS', 'Maïs'), ('SOJA', 'Soja'), ('ANANAS', 'Ananas'), ('RIZ', 'Riz')], max_length=20)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recolte', models.DateField(auto_now_add=True)),
                ('est_valide', models.BooleanField(default=False)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_recoltes.parcelle')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
