# Generated by Django 5.2.7 on 2026-01-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_membres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
