# Generated by Django 5.2.7 on 2026-01-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('MAIS', 'Maïs'), ('SOJA', 'Soja'), ('ANANAS', 'Ananas'), ('RIZ', 'Riz')], max_length=20, unique=True, verbose_name='Type de Produit')),
                ('quantite_totale', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Quantité Totale (kg)')),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Global',
                'verbose_name_plural': 'Stocks Globaux',
            },
        ),
    ]
